#asks the user numbers and calculation 
#getting input from the user using gets.chomp
puts " Enter first number:"
first_number = gets.chomp.to_i
puts " Enter your desired operation (+ , -, *):"
operation_sign = gets.chomp
puts " Enter second number:"
second_number = gets.chomp.to_i
#calling the method withing the input generated by the user to loop into the desired calculation.
def calculate (first_number, operation_sign, second_number)
  if operation_sign == "+"
     result = first_number + second_number
  elsif operation_sign == "-"
     result1 = first_number - second_number
  elsif operation_sign == "*"
    result2 = first_number * second_number
  end
end
p calculate(first_number, operation_sign, second_number)

puts "Type yes to run another calculation or done to end: "
    run_calculator = gets.chomp
    if run_calculator == "yes"  
     while run_calculator == yes do calculate()

      #current_calculation = calculate() 
    elseif run_calculator != "yes"
      puts "Thanks for using Calculus"
    end
end

while run_calculator == "yes"
  puts "Please enter a calculation"
  user_input = gets.chomp
  # run calculation method
  # store calculation
  # print calculation 
  puts "Another calculation? yes or no"
  run_calculator = gets.chomp
end